ubuntu@ansible-agent1:~$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search ap-south-1.compute.internal
ubuntu@ansible-agent1:~$ 


ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ cat inventory.txt 
[agent1]
172.31.31.81 ansible_connection=ssh 

[agent2]
172.31.30.160 ansible_connection=ssh

[allservers:children]
agent1
agent2


ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ cat playbook.resolvconf.yml 
-
  name: Play1
  hosts: all 
  become: yes
  tasks:
    -
      name: Update an entry into resolv.conf file
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 100.100.10.10'
ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ 
ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search ap-south-1.compute.internal
ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ ansible-playbook playbook.resolvconf.yml -i inventory.txt 

PLAY [Play1] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.31.81]
fatal: [172.31.30.160]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 172.31.30.160 port 22: Connection timed out\r\n", "unreachable": true}

TASK [Update an entry into resolv.conf file] *************************************************************************************************************************************
changed: [172.31.31.81]
	to retry, use: --limit @/home/ubuntu/ansible/Lab-7-lineinfile/playbook.resolvconf.retry

PLAY RECAP ***********************************************************************************************************************************************************************
172.31.30.160              : ok=0    changed=0    unreachable=1    failed=0   
172.31.31.81               : ok=2    changed=1    unreachable=0    failed=0   

ubuntu@ansible-master:~/ansible/Lab-7-lineinfile$ 

// CROSS VERIFY AFTER EXECUTION:

ubuntu@ansible-agent1:~$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search ap-south-1.compute.internal
nameserver 100.100.10.10
ubuntu@ansible-agent1:~$ 


